### ISSUE TITLE
Forkable QuestPDF versions

### ISSUE THREAD

**Issue by tb-mtg** [FossPDF/FossPDF.Net#2]
At the bottom of [this](https://github.com/QuestPDF/QuestPDF/issues/574#issuecomment-1769206185) issue comment relating to QuestPDF Re-licensing, the repo owner @MarcinZiabek suggested that everything released with the 2022 major version can be forked.

> @DaveVdE At this moment, I am still supporting pure-MIT versions (everything released with the 2022 major version). I am planning to sunset those releases somewhere in Q1 2024. Of course, not every change/improvement/fix can be back-ported. Until then, I will work hard to make new versions as viable as possible. Also, I am not planning to stop/block anybody who is willing to support a fork.

At this point in time, the latest version available on nuget.org is [2022.12.7](https://www.nuget.org/packages/QuestPDF/2022.12.7) which has the MIT license. 

Not sure but looks like this repo may have been forked on version 2022.12.5. If so, could update it the newer version and create a new NuGet version.

**Comment by MarcinZiabek** [comment]
All fixes published within the `2022.12.X` releases have been backported from main and managed in the https://github.com/QuestPDF/QuestPDF/tree/2022.12.X-support branch.

**Comment by lol768** [comment]
Thanks both. I've only recently (last week or two) started work on the project using this library, which is why it's sat without fixes re-incoporated into it.

I'll aim to get the latest fixes from the branch backported in.
